export { Allocations } from './allocations/allocations'
export { Dashboard } from './dashboard/dashboard'
export { Categories } from './categories/categories'
export { Employees } from './employees/employees'
export { Equipments } from './equipments/equipments'
export { Logs } from './logs/logs'
export { Login } from './login/login'
